project_name: gonetmon

builds:
  - binary: gnm

    main: ./cmd/gnm/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
      - 6
      - 5

docker_manifests:
  - name_template: 'rafadotel/gonetmon:latest'
    image_templates:
      - 'rafadotel/gonetmon:{{ .Tag }}-amd64'
      - 'rafadotel/gonetmon:{{ .Tag }}-arm64'
      - 'rafadotel/gonetmon:{{ .Tag }}-armv7'
  - name_template: 'rafadotel/gonetmon:{{ .Tag }}'
    image_templates:
      - 'rafadotel/gonetmon:{{ .Tag }}-amd64'
      - 'rafadotel/gonetmon:{{ .Tag }}-arm64'
      - 'rafadotel/gonetmon:{{ .Tag }}-armv7'
  - name_template: 'rafadotel/gonetmon:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - 'rafadotel/gonetmon:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'rafadotel/gonetmon:v{{ .Major }}.{{ .Minor }}-arm64'
      - 'rafadotel/gonetmon:v{{ .Major }}.{{ .Minor }}-armv7'

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'rafadotel/gonetmon:latest-amd64'
      - 'rafadotel/gonetmon:{{ .Tag }}-amd64'
      - 'rafadotel/gonetmon:v{{ .Major }}.{{ .Minor }}-amd64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Golang Network Monitor'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation=https://github.com/rafa-dot-el/gonetmon'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/amd64'

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'rafadotel/gonetmon:latest-arm64'
      - 'rafadotel/gonetmon:{{ .Tag }}-arm64'
      - 'rafadotel/gonetmon:v{{ .Major }}.{{ .Minor }}-arm64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Golang Network Monitor'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation=https://github.com/rafa-dot-el/gonetmon'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/arm64'

  - use: buildx
    goos: linux
    goarch: arm
    goarm: '7'
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'rafadotel/gonetmon:latest-armv7'
      - 'rafadotel/gonetmon:{{ .Tag }}-armv7'
      - 'rafadotel/gonetmon:v{{ .Major }}.{{ .Minor }}-armv7'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Golang Network Monitor'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation=https://github.com/rafa-dot-el/gonetmon'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/arm/v7'

changelog:
  skip: false
  use: github
  sort: asc
  abbrev: -1
  groups:
    - title: Features
      regexp: '^feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Chores'
      regexp: '^chore: .+$'
      order: 2
  filters:
    exclude:
      - '^docs:'
      - typo
      - (?i)foo
